services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - backend

  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --timeout-keep-alive 300 --timeout-graceful-shutdown 30
    ports:
      - "${PORT:-8000}:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://myuser:mypassword@db:5432/mydb
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backend:
