"""phone number unique

Revision ID: 126bec7c9e21
Revises: 701a765904b5
Create Date: 2025-10-16 21:30:42.111754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126bec7c9e21'
down_revision: Union[str, Sequence[str], None] = '701a765904b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_one_time_codes_phone_number'), table_name='one_time_codes')
    op.create_index(op.f('ix_one_time_codes_phone_number'), 'one_time_codes', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_one_time_codes_phone_number'), table_name='one_time_codes')
    op.create_index(op.f('ix_one_time_codes_phone_number'), 'one_time_codes', ['phone_number'], unique=False)
    # ### end Alembic commands ###
