"""Add otp expiration

Revision ID: 5873c6b88913
Revises: 8ae1adf044b5
Create Date: 2025-10-22 11:48:42.168786

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5873c6b88913"
down_revision: Union[str, Sequence[str], None] = "8ae1adf044b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM one_time_codes")
    op.add_column(
        "one_time_codes",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.drop_index(op.f("ix_one_time_codes_code"), table_name="one_time_codes")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=True)
    op.create_foreign_key(
        None, "refresh_tokens", "refresh_tokens", ["parent_token_id"], ["id"]
    )
    op.create_foreign_key(None, "refresh_tokens", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.create_index(
        op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_one_time_codes_code"), "one_time_codes", ["code"], unique=False
    )
    op.drop_column("one_time_codes", "expires_at")
    # ### end Alembic commands ###
