"""Add otp

Revision ID: 701a765904b5
Revises: 575239f77f60
Create Date: 2025-10-16 21:00:23.480834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701a765904b5'
down_revision: Union[str, Sequence[str], None] = '575239f77f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('one_time_codes',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('phone_number', 'code')
    )
    op.create_index(op.f('ix_one_time_codes_code'), 'one_time_codes', ['code'], unique=False)
    op.create_index(op.f('ix_one_time_codes_phone_number'), 'one_time_codes', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_one_time_codes_phone_number'), table_name='one_time_codes')
    op.drop_index(op.f('ix_one_time_codes_code'), table_name='one_time_codes')
    op.drop_table('one_time_codes')
    # ### end Alembic commands ###
