"""Drop refresh token family primary key constraint

Revision ID: f7aa6f22eed4
Revises: 5873c6b88913
Create Date: 2025-10-22 12:15:36.470603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7aa6f22eed4'
down_revision: Union[str, Sequence[str], None] = '5873c6b88913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
